/** იგივე სია პროფილში და ონბორდინგში — უმეტესობა რიგით. */
export const PROFILE_LANGUAGE_OPTIONS: readonly string[] = [
  "ქართული",
  "English",
  "Русский",
  "Deutsch",
  "Français",
  "Español",
  "Italiano",
  "Português",
  "Nederlands",
  "Polski",
  "Українська",
  "Türkçe",
  "العربية",
  "हिन्दी",
  "中文 (Mandarin)",
  "日本語",
  "한국어",
  "Svenska",
  "Norsk",
  "Dansk",
  "Suomi",
  "Čeština",
  "Magyar",
  "Română",
  "Български",
  "Ελληνικά",
  "עברית",
  "فارسی",
] as const
