export const queryKeys = {
  homeFeed: ["home-feed"] as const,
  homeStats: ["home-stats"] as const,
  listingsPage: (page: number) => ["listings-page", page] as const,
  listingsCatalog: (searchQuery = "") => ["listings-catalog", searchQuery] as const,
  jobsPage: (category: string, page: number) => ["jobs-page", category, page] as const,
  jobsCatalog: (category: string, searchQuery = "") => ["jobs-catalog", category, searchQuery] as const,
  recommendedJobs: (freelancerId: string) => ["recommended-jobs", freelancerId] as const,
  browseFreelancers: ["browse-freelancers"] as const,
  browseCatalog: ["browse-catalog"] as const,
  hirers: ["hirers"] as const,
  hirerIndustries: ["hirer-industries"] as const,
  hirerPublic: (id: string) => ["hirer-public", id] as const,
  freelancerProfile: (slug: string) => ["freelancer-profile", slug] as const,
  listingDetail: (id: string) => ["listing-detail", id] as const,
  jobDetail: (id: string) => ["job-detail", id] as const,
  savedItems: (userId: string) => ["saved-items", userId] as const,
  publicCv: (slug: string) => ["public-cv", slug] as const,
  cvGenerator: (userId: string) => ["cv-generator", userId] as const,
  dashboard: (userId: string) => ["dashboard", userId] as const,
  messagesList: (userId: string) => ["messages-list", userId] as const,
  messagesThread: (conversationId: string) => ["messages-thread", conversationId] as const,
  profile: (userId: string) => ["profile", userId] as const,
  postJob: (userId: string, jobId?: string) => ["post-job", userId, jobId ?? "new"] as const,
  listingForm: (userId: string, listingId?: string) => ["listing-form", userId, listingId ?? "new"] as const,
  onboarding: (userId: string) => ["onboarding", userId] as const,
  forumPosts: (filters: { category?: string; subcategory?: string; mine?: boolean; userId?: string }) =>
    ["forum-posts", filters] as const,
  forumPostDetail: (postId: string) => ["forum-post-detail", postId] as const,
}
