-- Georgian labels for marketplace specializations (subcategories.name_ka).
-- Prior seeds copied name_en into name_ka; this migration restores proper ka labels.
-- Idempotent: safe to re-run.

UPDATE public.subcategories AS s
SET name_ka = v.name_ka
FROM (
  VALUES
    ('ai-automation-ai-development-ai-chatbots', 'AI ჩატბოტები'),
    ('ai-automation-ai-development-chatgpt-integration', 'ChatGPT ინტეგრაცია'),
    ('ai-automation-ai-development-computer-vision', 'კომპიუტერული მხედველობა'),
    ('ai-automation-ai-development-machine-learning-solutions', 'მანქანური სწავლების გადაწყვეტები'),
    ('ai-automation-ai-development-natural-language-processing', 'ბუნებრივი ენის დამუშავება'),
    ('ai-automation-data-science-business-intelligence', 'ბიზნეს ინტელექტი'),
    ('ai-automation-data-science-data-analysis', 'მონაცემთა ანალიზი'),
    ('ai-automation-data-science-data-visualization', 'მონაცემთა ვიზუალიზაცია'),
    ('ai-automation-data-science-predictive-analytics', 'პროგნოზული ანალიტიკა'),
    ('ai-automation-workflow-automation-crm-automation', 'CRM ავტომაცია'),
    ('ai-automation-workflow-automation-make-com-workflows', 'Make.com workflow-ები'),
    ('ai-automation-workflow-automation-n8n-automation', 'N8N ავტომაცია'),
    ('ai-automation-workflow-automation-process-automation', 'პროცესის ავტომაცია'),
    ('ai-automation-workflow-automation-zapier-integration', 'Zapier ინტეგრაცია'),
    ('automotive-auto-services-auto-electrical', 'ავტო ელექტრიკა'),
    ('automotive-auto-services-auto-repair', 'ავტომობილის შეკეთება'),
    ('automotive-auto-services-bodywork-paint', 'კუზოვნი სამუშაო და შეღებვა'),
    ('automotive-auto-services-car-detailing', 'ავტომობილის გაპრიალება'),
    ('automotive-auto-services-car-inspection', 'ავტომობილის შემოწმება'),
    ('automotive-auto-services-mobile-mechanic', 'მობილური მექანიკოსი'),
    ('automotive-auto-services-tire-services', 'შინსების სერვისი'),
    ('automotive-driving-services-airport-transfers', 'აეროპორტის ტრანსფერი'),
    ('automotive-driving-services-driver-services', 'მძღოლის მომსახურება'),
    ('automotive-driving-services-driving-lessons', 'მართვის გაკვეთილები'),
    ('business-services-accounting-finance-bookkeeping', 'ბუღალტერია'),
    ('business-services-accounting-finance-financial-analysis', 'ფინანსური ანალიზი'),
    ('business-services-accounting-finance-invoice-management', 'ინვოისების მართვა'),
    ('business-services-accounting-finance-payroll-management', 'ხელფასის მართვა'),
    ('business-services-accounting-finance-tax-preparation', 'საგადასახადო დეკლარაცია'),
    ('business-services-administrative-calendar-management', 'კალენდრის მართვა'),
    ('business-services-administrative-customer-support', 'მომხმარებელთა მხარდაჭერა'),
    ('business-services-administrative-data-entry', 'მონაცემთა შეყვანა'),
    ('business-services-administrative-email-management', 'ელ. ფოსტის მართვა'),
    ('business-services-administrative-live-chat-support', 'Live Chat მხარდაჭერა'),
    ('business-services-administrative-virtual-assistant', 'ვირტუალური ასისტენტი'),
    ('business-services-business-consulting-business-planning', 'ბიზნეს გეგმა'),
    ('business-services-business-consulting-financial-planning', 'ფინანსური დაგეგმვა'),
    ('business-services-business-consulting-market-research', 'ბაზრის კვლევა'),
    ('business-services-business-consulting-startup-consulting', 'სტარტაპ კონსულტაცია'),
    ('business-services-business-consulting-strategy-consulting', 'სტრატეგიის კონსულტაცია'),
    ('business-services-legal-services-company-registration', 'კომპანიის რეგისტრაცია'),
    ('business-services-legal-services-contract-review', 'ხელშეკრულების განხილვა'),
    ('business-services-legal-services-document-preparation', 'დოკუმენტების მომზადება'),
    ('business-services-legal-services-legal-consulting', 'იურიდიული კონსულტაცია'),
    ('design-creative-3d-design-animation', '3D ანიმაცია'),
    ('design-creative-3d-design-architectural-visualization', 'არქიტექტურული ვიზუალიზაცია'),
    ('design-creative-3d-design-modeling', '3D მოდელირება'),
    ('design-creative-3d-design-printing-design', '3D ბეჭდვის დიზაინი'),
    ('design-creative-3d-design-product-visualization', 'პროდუქტის ვიზუალიზაცია'),
    ('design-creative-graphic-design-brand-identity', 'ბრენდის იდენტობა'),
    ('design-creative-graphic-design-business-card-design', 'ვიზიტკის დიზაინი'),
    ('design-creative-graphic-design-logo-design', 'ლოგოს დიზაინი'),
    ('design-creative-graphic-design-menu-design', 'მენიუს დიზაინი'),
    ('design-creative-graphic-design-packaging-design', 'შეფუთვის დიზაინი'),
    ('design-creative-graphic-design-poster-flyer-design', 'პოსტერის და ფლაიერის დიზაინი'),
    ('design-creative-graphic-design-print-design', 'ბეჭდვის დიზაინი'),
    ('design-creative-graphic-design-social-media-graphics', 'სოც. მედიის გრაფიკა'),
    ('design-creative-illustration-art-character-design', 'პერსონაჟის დიზაინი'),
    ('design-creative-illustration-art-childrens-book-illustration', 'საბავშვო წიგნის ილუსტრაცია'),
    ('design-creative-illustration-art-comic-art', 'კომიქსის ხელოვნება'),
    ('design-creative-illustration-art-digital-illustration', 'ციფრული ილუსტრაცია'),
    ('design-creative-illustration-art-infographics', 'ინფოგრაფიკა'),
    ('design-creative-illustration-art-technical-illustration', 'ტექნიკური ილუსტრაცია'),
    ('design-creative-interior-design-3d-room-design', '3D ოთახის დიზაინი'),
    ('design-creative-interior-design-commercial-interior-design', 'კომერციული ინტერიერის დიზაინი'),
    ('design-creative-interior-design-furniture-design', 'ავეჯის დიზაინი'),
    ('design-creative-interior-design-residential-interior-design', 'საცხოვრებელი ინტერიერის დიზაინი'),
    ('design-creative-ui-ux-design-design-systems', 'დიზაინ სისტემები'),
    ('design-creative-ui-ux-design-mobile-app-ui-ux', 'მობილური აპის UI/UX'),
    ('design-creative-ui-ux-design-usability-testing', 'გამოყენებადობის ტესტირება'),
    ('design-creative-ui-ux-design-user-research', 'მომხმარებლის კვლევა'),
    ('design-creative-ui-ux-design-website-ui-ux', 'ვებსაიტის UI/UX'),
    ('design-creative-ui-ux-design-wireframing-prototyping', 'Wireframe და Prototyping'),
    ('home-services-childcare-after-school-care', 'სკოლის შემდგომი მოვლა'),
    ('home-services-childcare-babysitting', 'ბავშვის მოვლა'),
    ('home-services-childcare-homework-help', 'დავალებებში დახმარება'),
    ('home-services-childcare-nanny-services', 'ნიანის მომსახურება'),
    ('home-services-cleaning-deep-cleaning', 'ღრმა დასუფთავება'),
    ('home-services-cleaning-house-cleaning', 'სახლის დასუფთავება'),
    ('home-services-cleaning-move-in-move-out-cleaning', 'გადასვლის დასუფთავება'),
    ('home-services-cleaning-office-cleaning', 'ოფისის დასუფთავება'),
    ('home-services-cleaning-window-cleaning', 'ფანჯრების რეცხვა'),
    ('home-services-elderly-care-dementia-care', 'დემენციის მოვლა'),
    ('home-services-elderly-care-elderly-companion', 'ხანდაზმულის კომპანიონი'),
    ('home-services-elderly-care-home-care-assistant', 'სახლში მოვლის ასისტენტი'),
    ('home-services-elderly-care-nursing-care', 'მედიცინული მოვლა'),
    ('home-services-home-repair-maintenance-appliance-repair', 'ტექნიკის შეკეთება'),
    ('home-services-home-repair-maintenance-carpentry', 'მარანგული სამუშაო'),
    ('home-services-home-repair-maintenance-electrical-work', 'ელექტრო სამუშაო'),
    ('home-services-home-repair-maintenance-general-handyman', 'ხელოსანი'),
    ('home-services-home-repair-maintenance-hvac-repair', 'HVAC შეკეთება'),
    ('home-services-home-repair-maintenance-locksmith-services', 'საკეტების სერვისი'),
    ('home-services-home-repair-maintenance-painting', 'მოხატვა'),
    ('home-services-home-repair-maintenance-plumbing', 'სანტეხნიკა'),
    ('home-services-moving-delivery-delivery-services', 'მიწოდების სერვისი'),
    ('home-services-moving-delivery-furniture-assembly', 'ავეჯის აწყობა'),
    ('home-services-moving-delivery-moving-services', 'გადატანის სერვისი'),
    ('home-services-moving-delivery-packing-services', 'შეფუთვის სერვისი'),
    ('home-services-pet-services-dog-walking', 'ძაღლის გასეირნება'),
    ('home-services-pet-services-pet-grooming', 'ცხოველის გრუმინგი'),
    ('home-services-pet-services-pet-sitting', 'ცხოველის მოვლა'),
    ('home-services-pet-services-pet-training', 'ცხოველის ტრენირება'),
    ('home-services-pet-services-veterinary-consultation-online', 'ვეტერინარული კონსულტაცია (Online)'),
    ('lifestyle-personal-beauty-services-eyebrow-lash-specialist', 'წარბის/წმყვანის სპეციალისტი'),
    ('lifestyle-personal-beauty-services-hair-stylist', 'დალაქი'),
    ('lifestyle-personal-beauty-services-makeup-artist', 'ვიზაჟისტი'),
    ('lifestyle-personal-beauty-services-nail-technician', 'მანიკიური'),
    ('lifestyle-personal-health-fitness-fitness-coaching-online', 'Fitness Coaching (Online)'),
    ('lifestyle-personal-health-fitness-meal-planning', 'კვების დაგეგმვა'),
    ('lifestyle-personal-health-fitness-nutrition-planning', 'კვების დაგეგმვა'),
    ('lifestyle-personal-health-fitness-personal-training', 'პერსონალური ტრენირება'),
    ('lifestyle-personal-health-fitness-yoga-instruction', 'იოგა'),
    ('lifestyle-personal-life-coaching-business-coaching', 'ბიზნეს Coaching'),
    ('lifestyle-personal-life-coaching-career-coaching', 'კარიერის Coaching'),
    ('lifestyle-personal-life-coaching-life-coaching', 'Life Coaching'),
    ('lifestyle-personal-life-coaching-relationship-coaching', 'ურთიერთობის Coaching'),
    ('marketing-advertising-branding-brand-guidelines', 'ბრენდის Guidelines'),
    ('marketing-advertising-branding-brand-strategy', 'ბრენდის სტრატეგია'),
    ('marketing-advertising-branding-competitor-analysis', 'კონკურენტების ანალიზი'),
    ('marketing-advertising-branding-market-research', 'ბაზრის კვლევა'),
    ('marketing-advertising-content-marketing-blog-management', 'ბლოგის მართვა'),
    ('marketing-advertising-content-marketing-content-strategy', 'კონტენტის სტრატეგია'),
    ('marketing-advertising-content-marketing-newsletter-management', 'Newsletter-ის მართვა'),
    ('marketing-advertising-content-marketing-social-media-content', 'სოც. მედიის კონტენტი'),
    ('marketing-advertising-digital-marketing-affiliate-marketing', 'Affiliate მარკეტინგი'),
    ('marketing-advertising-digital-marketing-email-marketing', 'ელ. ფოსტის მარკეტინგი'),
    ('marketing-advertising-digital-marketing-facebook-instagram-ads', 'Facebook/Instagram რეკლამა'),
    ('marketing-advertising-digital-marketing-google-ads-ppc', 'Google Ads (PPC)'),
    ('marketing-advertising-digital-marketing-influencer-marketing', 'ინფლუენსერ მარკეტინგი'),
    ('marketing-advertising-digital-marketing-social-media-marketing', 'სოც. მედიის მარკეტინგი'),
    ('marketing-advertising-digital-marketing-tiktok-marketing', 'TikTok მარკეტინგი'),
    ('marketing-advertising-seo-keyword-research', 'საკვანძო სიტყვების კვლევა'),
    ('marketing-advertising-seo-local-seo', 'Local SEO'),
    ('marketing-advertising-seo-off-page-seo', 'Off-page SEO'),
    ('marketing-advertising-seo-on-page-seo', 'On-page SEO'),
    ('marketing-advertising-seo-seo-audits', 'SEO აუდიტი'),
    ('marketing-advertising-seo-technical-seo', 'Technical SEO'),
    ('music-audio-music-production-audio-editing', 'აუდიო რედაქტირება'),
    ('music-audio-music-production-beat-making', 'Beat Making'),
    ('music-audio-music-production-mixing-mastering', 'Mixing & Mastering'),
    ('music-audio-music-production-music-composition', 'მუსიკის კომპოზიცია'),
    ('music-audio-music-production-podcast-editing', 'Podcast-ის რედაქტირება'),
    ('music-audio-sound-design-film-scoring', 'Film Scoring'),
    ('music-audio-sound-design-foley', 'Foley'),
    ('music-audio-sound-design-game-audio', 'Game Audio'),
    ('music-audio-sound-design-sound-effects', 'ხმის ეფექტები'),
    ('music-audio-voice-services-audio-book-recording', 'Audiobook-ის ჩაწერა'),
    ('music-audio-voice-services-dubbing', 'დუბლაჟი'),
    ('music-audio-voice-services-narration', 'ნარაცია'),
    ('music-audio-voice-services-voice-over-english', 'Voice Over (ინგლისური)'),
    ('music-audio-voice-services-voice-over-georgian', 'Voice Over (ქართული)'),
    ('photography-commercial-photography-fashion-photography', 'მოდის ფოტოგრაფია'),
    ('photography-commercial-photography-food-photography', 'საკვების ფოტოგრაფია'),
    ('photography-commercial-photography-portrait-photography', 'პორტრეტის ფოტოგრაფია'),
    ('photography-commercial-photography-product-photography', 'პროდუქტის ფოტოგრაფია'),
    ('photography-commercial-photography-real-estate-photography', 'უძრავი ქონების ფოტოგრაფია'),
    ('photography-event-photography-birthday-photography', 'დაბადების დღის ფოტოგრაფია'),
    ('photography-event-photography-conference-photography', 'კონფერენციის ფოტოგრაფია'),
    ('photography-event-photography-corporate-events', 'კორპორატიული ღონისძიებები'),
    ('photography-event-photography-wedding-photography', 'ქორწილის ფოტოგრაფია'),
    ('photography-photo-editing-background-removal', 'ფონის წაშლა'),
    ('photography-photo-editing-color-correction', 'ფერის კორექცია'),
    ('photography-photo-editing-photo-restoration', 'ფოტოს რესტავრაცია'),
    ('photography-photo-editing-photo-retouching', 'ფოტოს რეტუშირება'),
    ('technology-development-blockchain-cryptocurrency-development', 'კრიპტოვალუტის დეველოპმენტი'),
    ('technology-development-blockchain-nft-development', 'NFT დეველოპმენტი'),
    ('technology-development-blockchain-smart-contract-development', 'Smart Contract დეველოპმენტი'),
    ('technology-development-blockchain-web3-applications', 'Web3 აპლიკაციები'),
    ('technology-development-game-game-design', 'თამაშის დიზაინი'),
    ('technology-development-game-mobile-games', 'მობილური თამაშები'),
    ('technology-development-game-pc-console-games', 'PC/კონსოლის თამაშები'),
    ('technology-development-game-unity-development', 'Unity დეველოპმენტი'),
    ('technology-development-game-unreal-engine', 'Unreal Engine'),
    ('technology-development-mobile-android-development', 'Android დეველოპმენტი'),
    ('technology-development-mobile-app-maintenance-updates', 'აპის მოვლა და განახლება'),
    ('technology-development-mobile-cross-platform-apps', 'კროს-პლატფორმული აპები'),
    ('technology-development-mobile-flutter-development', 'Flutter დეველოპმენტი'),
    ('technology-development-mobile-ios-development', 'iOS დეველოპმენტი'),
    ('technology-development-mobile-react-native-development', 'React Native დეველოპმენტი'),
    ('technology-development-software-api-development-integration', 'API დეველოპმენტი და ინტეგრაცია'),
    ('technology-development-software-cloud-solutions-aws-azure-gcp', 'ღრუბლოვანი გადაწყვეტები (AWS, Azure, GCP)'),
    ('technology-development-software-custom-software-solutions', 'პროგრამული გადაწყვეტები'),
    ('technology-development-software-database-design', 'მონაცემთა ბაზის დიზაინი'),
    ('technology-development-software-desktop-applications', 'დესკტოპ აპლიკაციები'),
    ('technology-development-web-backend-development', 'ბექენდ დეველოპმენტი'),
    ('technology-development-web-frontend-development', 'ფრონტენდ დეველოპმენტი'),
    ('technology-development-web-full-stack-development', 'Full-stack დეველოპმენტი'),
    ('technology-development-web-landing-pages', 'ლენდინგ გვერდები'),
    ('technology-development-web-shopify-ecommerce-development', 'Shopify/E-commerce დეველოპმენტი'),
    ('technology-development-web-web-applications', 'ვებ აპლიკაციები'),
    ('technology-development-web-website-maintenance', 'ვებსაიტის მოვლა'),
    ('technology-development-web-wordpress-development', 'WordPress დეველოპმენტი'),
    ('tutoring-education-academic-tutoring-biology', 'ბიოლოგია'),
    ('tutoring-education-academic-tutoring-chemistry-tutoring', 'ქიმიის რეპეტიტორი'),
    ('tutoring-education-academic-tutoring-english-language', 'ინგლისური ენა'),
    ('tutoring-education-academic-tutoring-georgian-language', 'ქართული ენა'),
    ('tutoring-education-academic-tutoring-history', 'ისტორია'),
    ('tutoring-education-academic-tutoring-math-tutoring', 'მათემატიკის რეპეტიტორი'),
    ('tutoring-education-academic-tutoring-physics-tutoring', 'ფიზიკის რეპეტიტორი'),
    ('tutoring-education-professional-training-design-lessons', 'დიზაინის გაკრეთილები'),
    ('tutoring-education-professional-training-language-lessons', 'ენის გაკვეთილები'),
    ('tutoring-education-professional-training-music-lessons', 'მუსიკის გაკვეთილები'),
    ('tutoring-education-professional-training-programming-lessons', 'პროგრამირების გაკვეთილები'),
    ('tutoring-education-test-preparation-sat-act-prep', 'SAT/ACT მომზადება'),
    ('tutoring-education-test-preparation-toefl-ielts-prep', 'TOEFL/IELTS მომზადება'),
    ('tutoring-education-test-preparation-unified-exams-prep', 'ერთიანი გამოცდვების მომზადება'),
    ('tutoring-education-test-preparation-university-entrance-prep', 'საუნივერსიტეტო შესადზლებლობის მომზადება'),
    ('video-animation-animation-2d-animation', '2D ანიმაცია'),
    ('video-animation-animation-3d-animation', '3D ანიმაცია'),
    ('video-animation-animation-explainer-videos', 'Explainer ვიდეო'),
    ('video-animation-animation-logo-animation', 'ლოგოს ანიმაცია'),
    ('video-animation-animation-motion-graphics', 'Motion Graphics'),
    ('video-animation-animation-whiteboard-animation', 'Whiteboard ანიმაცია'),
    ('video-animation-post-production-color-grading', 'Color Grading'),
    ('video-animation-post-production-sound-design', 'ხმის დიზაინი'),
    ('video-animation-post-production-subtitling-captioning', 'სუბტიტრები და Caption-ები'),
    ('video-animation-post-production-visual-effects-vfx', 'Visual Effects (VFX)'),
    ('video-animation-video-production-drone-videography', 'Drone-ით გადაღება'),
    ('video-animation-video-production-event-videography', 'ღონისძიების ვიდეოგრაფია'),
    ('video-animation-video-production-product-videos', 'პროდუქტის ვიდეო'),
    ('video-animation-video-production-promotional-videos', 'სარეკლამო ვიდეო'),
    ('video-animation-video-production-real-estate-videos', 'უძრავი ქონების ვიდეო'),
    ('video-animation-video-production-video-editing', 'ვიდეო მონტაჟი'),
    ('video-animation-video-production-wedding-videography', 'ქორწილის ვიდეოგრაფია'),
    ('writing-translation-editing-proofreading-academic-editing', 'აკადემიური რედაქტირება'),
    ('writing-translation-editing-proofreading-book-editing', 'წიგნის რედაქტირება'),
    ('writing-translation-editing-proofreading-copy-editing', 'რედაქტირება'),
    ('writing-translation-editing-proofreading-proofreading', 'კორექტურა'),
    ('writing-translation-translation-document-translation', 'დოკუმენტის თარგმანი'),
    ('writing-translation-translation-georgian-english-translation', 'ქართული-ინგლისური თარგმანი'),
    ('writing-translation-translation-georgian-russian-translation', 'ქართული-რუსული თარგმანი'),
    ('writing-translation-translation-georgian-turkish-translation', 'ქართული-თურქული თარგმანი'),
    ('writing-translation-translation-legal-translation', 'იურიდიული თარგმანი'),
    ('writing-translation-translation-medical-translation', 'მედიცინული თარგმანი'),
    ('writing-translation-translation-website-localization', 'ვებსაიტის ლოკალიზაცია'),
    ('writing-translation-writing-article-writing', 'სტატიების წერა'),
    ('writing-translation-writing-blog-writing', 'ბლოგის წერა'),
    ('writing-translation-writing-content-writing', 'კონტენტის წერა'),
    ('writing-translation-writing-copywriting', 'კოპირაიტინგი'),
    ('writing-translation-writing-creative-writing', 'კრეატიული წერა'),
    ('writing-translation-writing-email-copywriting', 'ელ. ფოსტის კოპირაიტინგი'),
    ('writing-translation-writing-press-releases', 'საანბაზმო განცხადებები'),
    ('writing-translation-writing-product-descriptions', 'პროდუქტის აღწერა'),
    ('writing-translation-writing-resume-cover-letter-writing', 'CV და საკომპანიო წერილი'),
    ('writing-translation-writing-technical-writing', 'ტექნიკური წერა')
) AS v(slug, name_ka)
WHERE s.slug = v.slug;
